# YAML config for !listgame and friends.
#

memory-use-limit-megabytes: 768

termcast:
  server: termcast.develz.org
  client-protocols:
    - telnet
    - http

##
# Maps query context names to table names. Thus !lg will query the `logrecord`
# table while !lm will query the `milestone` table. Note that each table
# name must also have an associated `name`-fields-with-type key.
query-contexts:
  lg:
    table: logrecord
  lm:
    table: milestone
    autojoin-context: lg

##
# Field name -> SQL name mappings; some field names have to be mapped to
# different names to avoid SQL keyword collisions.
sql-field-names:
  name: pname
  char: charabbrev
  str: sstr
  dex: sdex
  int: sint
  start: tstart
  end: tend
  time: ttime
  map: mapname
  offset: file_offset

##
# game types recognized by !lg and friends, mapped to the table name prefix.
# For instance, Crawl games will query `logrecord` and `milestone`, Sprint
# games will query `spr_logrecord` and `spr_milestone` and so on.
game-type-prefixes:
  crawl: ''
  sprint: spr_
  zotdef: zot_

default-game-type: crawl

orcs:
  - Agrik
  - Alork
  - Arbolt
  - Argrim
  - Arkwar
  - Berold
  - Bladwarg
  - Blodwig
  - Boderik
  - Bogdan
  - Boldo
  - Bolgrim
  - Borgk
  - Borgoth
  - Borgun
  - Boruk
  - Brandogh
  - Brunolf
  - Dorog
  - Garbold
  - Gorbash
  - Gorg
  - Gorm
  - Grimold
  - Harm
  - Hawl
  - Herok
  - Hilgar
  - Jorge
  - Judas
  - Koronagh
  - Learuk
  - Marbork
  - Margrim
  - Milork
  - Morguth
  - Morun
  - Murdo
  - Norbak
  - Nordag
  - Ognian
  - Ogrik
  - Okrist
  - Olfik
  - Olfrun
  - Oreg
  - Orgrim
  - Orik
  - Orkrul
  - Orkwin
  - Ortolf
  - Oruk
  - Rocco
  - Syrus
  - Thorok
  - Ugbert
  - Ugrim
  - Wardok
  - Wargath
  - Wargrak
  - Warrok
  - Worak
  - Wulfoc
  - Zorug

uniques:
  - Ijyb
  - Blork the orc
  - Blork
  - Urug
  - Erolcha
  - Snorg
  - Polyphemus
  - Adolf
  - Antaeus
  - Xtahua
  - Tiamat
  - Boris
  - Murray
  - Terence
  - Jessica
  - Sigmund
  - Edmund
  - Psyche
  - Donald
  - Michael
  - Joseph
  - Erica
  - Josephine
  - Harold
  - Norbert
  - Jozef
  - Agnes
  - Maud
  - Louise
  - Francis
  - Frances
  - Rupert
  - Wayne
  - Duane
  - Norris
  - Frederick
  - Margery
  - Mnoleg
  - Lom Lobon
  - Cerebov
  - Gloorx Vloq
  - Geryon
  - Dispater
  - Asmodeus
  - Ereshkigal
  - the royal jelly
  - the Lernaean hydra
  - Dissolution
  - Azrael
  - Prince Ribbit
  - Sonja
  - Ilsuiw
  - Nergalle
  - Saint Roka
  - Roxanne
  - Eustachio
  - Nessos
  - Dowan
  - Duvessa
  - Grum
  - Crazy Yiuf
  - Gastronok
  - Pikel
  - Menkaure
  - Khufu
  - Aizul
  - Purgy
  - Kirke
  - Maurice
  - Nikola
  - Mara
  - Grinder
  - Mennas
  - Chuck
  - the iron giant
  - Nellie
  - Wiglaf
  - Jory
  - Terpsichore
  - Ignacio
  - Fannar
  - Arachne
  - "Cigotuvi's Monster"
  - Jorgrun
  - Lamia
  - Pan
  - Sojobo

# Only used by !apt at the moment.
skills:
  - Fighting
  - Short Blades
  - Long Blades
  - Axes
  - Maces & Flails
  - Polearms
  - Staves
  - Slings
  - Bows
  - Crossbows
  - Throwing
  - Armour
  - Dodging
  - Stealth
  - Shields
  - Unarmed Combat
  - Spellcasting
  - Conjurations
  - Hexes
  - Charms
  - Summonings
  - Necromancy
  - Translocations
  - Transmutations
  - Fire Magic
  - Ice Magic
  - Air Magic
  - Earth Magic
  - Poison Magic
  - Invocations
  - Evocations
  - Experience
  - HP
  - MP

skill-abbreviations:
  crossbows: Xbows
  throwing: Throw
  dodging: Dodge
  spellcasting: Splcast
  conjurations: Conj
  enchantments: Ench
  summonings: Summ
  necromancy: Nec
  translocations: Tloc
  transmutations: Tmut
  divinations: Div
  invocations: Inv
  evocations: Evo
  experience: Exp
  hp: HP
  mp: MP
  'unarmed combat': UC

skill-expansions:
  pois: poison magic
  flails: maces & flails
  invo: invocations
  necro: necromancy
  tmut: transmutations
  armor: armour
  uc: unarmed combat

# Must include all variations of branch names here. Canonical names may be
# generated by place-fixups. Suffix the branch name with : to indicate that
# it has a depth. Suffix with [:] to indicate that this branch may or may
# not have a depth.
branches:
  - 'D:'
  - 'Orc:'
  - 'Elf:'
  - 'Lair:'
  - 'Depths:'
  - 'Swamp:'
  - 'Shoal:'
  - 'Shoals:'
  - 'Slime:'
  - 'Snake:'
  - 'Spider:'
  - 'Hive:'
  - 'Vault:'
  - 'Vaults:'
  - 'Crypt:'
  - 'Tomb:'
  - 'Dis:'
  - 'Geh:'
  - 'Coc:'
  - 'Tar:'
  - 'Zot:'
  - 'Ziggurat:'
  - 'Zig:'
  - 'Forest:'
  - Lab
  - Pan
  - Bazaar
  - Bzr
  - Hell
  - Blade
  - Temple
  - 'Abyss[:]'
  - WizLab
  - Sewer
  - Bailey
  - Minitom
  - Ossuary
  - Ice
  - IceCv
  - Volcano

god:
  ash: Ashenzari
  beo: Beogh
  che: Cheibriados
  ely: Elyvilon
  fed: Fedhas
  jiy: Jiyva
  kik: Kikubaaqudgha
  lug: Lugonu
  mak: Makhleb
  oka: Okawaru
  tro: Trog
  veh: Vehumet
  xom: Xom
  yre: Yredelemnul
  zin: Zin
  sif: Sif Muna
  tso: The Shining One
  nem: Nemelex Xobeh
  dit: Dithmengos

god-aliases:
  feawn: Fedhas

# * - dead species
species:
  Ce: Centaur
  Dg: Demigod
  Ds: Demonspawn
  Dr: Draconian
  El: Elf*
  Fe: Felid
  Gh: Ghoul
  Gn: Gnome*
  Ha: Halfling
  Hu: Human
  Ke: Kenku*
  Ko: Kobold
  Mf: Merfolk
  Mi: Minotaur
  Mu: Mummy
  Na: Naga
  OM: Ogre-Mage*
  Og: Ogre
  Sp: Spriggan
  Tr: Troll
  Vp: Vampire
  DD: Deep Dwarf
  HD: Hill Dwarf*
  MD: Mountain Dwarf*
  DE: Deep Elf
  GE: Grey Elf*
  HE: High Elf
  SE: Sludge Elf*
  HO: Hill Orc
  LO: Lava Orc
  Gr: [Gargoyle, Grotesk]
  Dj: Djinni
  Op: Octopode
  Te: Tengu
  Fo: Formicid
  VS: Vine Stalker

species-flavours:
  draconian:
    - base
    - red
    - white
    - green
    - yellow
    - grey
    - black
    - purple
    - mottled
    - pale

genus-species:
  draconian: draconian
  elven:
    - high elf
    - deep elf
    - sludge elf
  dwarven:
    - mountain dwarf
    - deep dwarf
  orcish:
    - hill orc
    - lava orc
  ogre: ogre

species-enum-map-override: {}

# * - dead class
classes:
  Ar: Artificer
  As: Assassin
  Be: Berserker
  Cj: Conjurer
  Cr: Crusader*
  En: Enchanter
  Fi: Fighter
  Gl: Gladiator
  He: Healer
  Hu: Hunter
  Mo: Monk
  Ne: Necromancer
  Pa: Paladin*
  Pr: Priest*
  Re: Reaver*
  St: Stalker*
  Su: Summoner
  Th: Thief*
  Tm: Transmuter
  Wn: Wanderer
  Wr: Warper
  Wz: Wizard
  AE: Air Elementalist
  EE: Earth Elementalist
  FE: Fire Elementalist
  IE: Ice Elementalist
  AK: Abyssal Knight
  CK: Chaos Knight
  DK: Death Knight
  VM: Venom Mage
  AM: Arcane Marksman
  Sk: Skald
  Jr: Jester*

column-aliases:
  maxsk: maxskills
  stat: status
  role: cls
  class: cls
  job: cls
  species: race
  sp: race
  r: race
  ktype: ktyp
  score: sc
  turns: turn
  skill: sk
  ch: char
  kmap: killermap
  c: cls
  cl: xl
  clev: xl
  type: verb
  gid: game_key
  game_id: game_key

place-fixups:
  '^shoals?\b(.*)': 'Shoals$1'
  '^dep(?:th)?\b(.*)': 'Depths$1'
  '^vaults?\b(.*)': 'Vaults$1'
  '^v\b(.*)': 'Vaults$1'
  '^ice$': 'IceCv'
  '^labyrinth$': 'Lab'

prefix-field-fixups:
  ktyp:
    win: winning
    won: winning
    acid: acid
    trap: trap
    drown: water
    leav: leaving
    left: leaving
    quit: quitting
    pois: pois
    cloud: cloud
    star: starvation
    mon: mon
    beam: beam
    lava: lava

# cdist and count are both count distinct
aggregate-functions:
  count_all:
    type: '*'
    expr: "COUNT(*)"
    return: I
  cdist:
    type: '*'
    expr: "COUNT(DISTINCT %s)"
    return: I
  count:
    type: '*'
    expr: "COUNT(DISTINCT %s)"
    return: I
  avg:
    types:
      - type: ETD
        return: '*'
      - type: I
        return: F
    preserve-unit: true
  median:
    type: I
    return: '*'
    preserve-unit: true
  max: '*'
  min: '*'
  sum:
    type: I
    return: I
    preserve-unit: true
  std:
    expr: "STDDEV(%s)"
    type: I
    return: F
  variance:
    type: I
    return: F

value-functions:
  now:
    types:
      - type: []
        return: D
    expr: "current_timestamp"
  int:
    type: '*'
    return: 'I'
    expr: "CAST(%s AS BIGINT)"
    summarisable: true
  interval:
    type: 'S'
    return: 'ETD'
    expr: "CAST(%s AS INTERVAL)"
    summarisable: true
  seconds_interval:
    type: ET
    return: ETD
    expr: "(%s * INTERVAL '1s')"
    summarisable: true
  interval_seconds:
    type: 'ETD'
    return: ET
    expr: "EXTRACT(EPOCH FROM %s)"
    summarisable: true
  length:
    type: 'S'
    return: 'I'
    expr: "LENGTH(%s)"
    summarisable: true
  log:
    type: 'I'
    return: 'F'
    expr: "TRUNC(LOG(%s) * 10) / 10"
    summarisable: true
  nhour:
    type: 'D'
    return: 'I'
    expr: "date_part('hour', %s)"
    summarisable: true
  nmin:
    type: 'D'
    return: 'I'
    expr: "date_part('minute', %s)"
    summarisable: true
  ndayofmonth:
    type: 'D'
    return: 'I'
    expr: "date_part('day', %s)"
    summarisable: true
  nmonth:
    type: 'D'
    return: 'I'
    expr: "date_part('month', %s)"
    summarisable: true
  ndayofweek:
    type: 'D'
    return: 'I'
    expr: "extract(dow from %s)"
    summarisable: true
  day:
    type: 'D'
    expr: "date_trunc('day', %s)"
    return: 'D'
    summarisable: true
    display-format: '%Y%m%d'
  month:
    type: 'D'
    expr: "date_trunc('month', %s)"
    summarisable: true
    display-format: '%Y%m'
  year:
    type: 'D'
    expr: "date_trunc('year', %s)"
    summarisable: true
    display-format: '%Y'
  vault:
    type: 'S'
    expr: "split_part(%s, '; ', 1)"
    summarisable: true
  part:
    types:
      - type: ['S', 'S', 'I']
        result: 'S'
    expr: "split_part(%s, :2, :3)"
  subvault:
    type: 'S'
    expr: "regexp_replace(%s, '^.*?; ', '')"
    summarisable: true
  size:
    type: 'S'
    summarisable: true
    return: 'I'
    expr: "case when %s = '' then 0 else length(regexp_replace(%s, '[^,]+', '', 'g')) + 1 end"

query-tables:
  - logrecord
  - milestone

# Multi-column indexes (single column indexes are annotated in the
# field name list)
logrecord-indexes:
  - [file, offset]

milestone-indexes:
  - [file, offset]
  - [verb, noun]

# Explicit lookup tables for fields that can reasonably share a lookup
# table.
#
# Note: lookup tables are shared across game types and across
# logrecord/milestone. Any field annotated ^ that does not have an
# explicit lookup table gets an implicit lookup table with the same
# name as the field.
lookup-tables:
  version:
    fields: [v]
    generated-fields:
      - vnumIH?^
  cversion:
    fields: [cv]
    generated-fields:
      - cvnumIH?^
  killer: [killer, ckiller, ikiller]
  map: [map, killermap]
  kaux: [kaux, ckaux]
  msg: [tmsg, vmsg]

type-categories:
  ETD: ETD
  ET: F
  VER: S
  MAP: S
  I: F
  F: F
  S: S
  '': S
  D: D
  '!': '!'

type-promotions:
  - [ETD, F]

sticky-types:
  - ETD

column-substitutes:
  ordered:
    v: vnum
    cv: cvnum

##
# Field type suffixes:
# - I (integer)
# - S (String, case sensitive)
# - IB (big integer)
# - IH (huge - 18 digits)
# - D (date+time)
#
# - ? (indexed)
# - * (not summarisable)
# - % (autoincrementing primary key)
# - ^ (foreign key into a table)
# - ! (negatable, aka boolean)
# - + (multi-valued)
logrecord-fields-with-type:
  - idIB%*
  - offsetIB*?
  - game_key?^
  - file?^
  - alpha!
  - src?^
  - vVER?^
  - cvVER?^
  - lv^
  - scIB?
  - nameS?^
  - race?^
  - crace?^
  - cls?^
  - char?^
  - xlI?
  - sk?^
  - sklevI?
  - title?^
  - ktyp?^
  - killer?^
  - ckiller?^
  - ikiller?^
  - kpath^
  - kmod^
  - kaux?^
  - ckaux?^
  - place?^
  - br^
  - lvlI
  - absdepthI
  - ltyp^
  - hpI?
  - mhpI?
  - mmhpI
  - damI
  - sdamI
  - tdamI
  - strI
  - intI
  - dexI
  - god?^
  - pietyI
  - penI
  - wizI
  - startD*?
  - endD*?
  - durET?
  - turnI?
  - uruneI?
  - nruneI?
  - tmsg^
  - vmsg^
  - splat!
  - rstart*?
  - rend*?
  - ntvI?
  - mapMAP?^
  - killermapMAP?^
  - mapdesc^
  - tiles!
  - goldI
  - goldfoundI
  - goldspentI
  - killsI
  - acI
  - evI
  - shI
  - autI
  - maxskills^+
  - status^+

milestone-fields-with-type:
  - idI%
  - game_key?^
  - offsetI*?
  - file?^
  - alpha!
  - src?^
  - vVER?^
  - cvVER?^
  - nameS?^
  - race?^
  - crace?^
  - cls?^
  - char?^
  - xlI?
  - sk?^
  - sklevI?
  - title?^
  - place?^
  - br^
  - lvlI
  - absdepthI
  - ltyp^
  - hpI?
  - mhpI?
  - mmhpI
  - strI
  - intI
  - dexI
  - god?^
  - durET
  - turnI?
  - uruneI?
  - nruneI?
  - timeD*?
  - rtime*?
  - startD*?
  - rstart*?
  - verb?^
  - nounS?^
  - milestone^
  - ntvI?
  - oplace^
  - tiles!
  - goldI
  - goldfoundI
  - goldspentI
  - killsI
  - acI
  - evI
  - shI
  - autI
  - maxskills^
  - status^

milestone-verb-mappings:
  unique: uniq
  enter: br.enter
  branch-finale: br.end

field-input-transforms: &inputtransforms
  sk:
    Translocation: Translocations
    Transmutation: Transmutations
    Transmigration: Transmutations

field-transforms:
  ktyp:
    poison: pois
    drown: water
    won: winning
    win: winning
    left: leaving
    leave: leaving
    quit: quitting
  status:
    berserk: berserking
    haste: hasted
    para: paralysed
    slow: slowed
    pois: ~poisoned
    regen: regenerating
    conf: confused
    noregen: non-regenerating
    inv: invisible
    defl: deflect missiles
    tel: about to teleport
  sk: &sk
    fi: Fighting
    nec: Necromancy
    evo: Evocations
    sho: Short Blades
    sbl: Short Blades
    ear: Earth Magic
    thr: Throwing
    dod: Dodging
    inv: invocations
    enc: Enchantments
    bow: Bows
    poi: Poison Magic
    t&d: Traps & Doors
    stab: Stabbing
    stav: Staves
    div: Divinations
    sli: Slings
    cross: Crossbows
    cbow: Crossbows
    hex: Hexes
    cha: Charms
    tloc: Translocations
    tmut: Transmutations
    tmig: Transmutations
    mace: Maces & Flails
    flai: Maces & Flails
    ice: Ice Magic
    fire: Fire Magic
    conj: Conjurations
    cj: Conjurations
    spc: Spellcasting
    spell: Spellcasting
    arm: Armour
    pole: Polearms
    pla: Polearms
    unar: Unarmed Combat
    summ: Summonings
    lbl: Long Blades
    long: Long Blades
    sh: Shields
    air: Air Magic

  maxskills:
    <<: *sk


##
# Fake query fields that are transformed into a real query field by code in
# query_synthetic.rb
fake-fields-with-type:
  - when*
  - game*

milestone-types:
  - abyss.enter
  - abyss.exit
  - rune
  - orb
  - orb.destroy
  - ghost
  - ghost.ban
  - ghost.pac
  - uniq
  - uniq.ban
  - uniq.pac
  - uniq.ens
  - br.enter
  - br.end
  - br.mid
  - br.exit
  - god.mollify
  - god.renounce
  - god.worship
  - god.maxpiety
  - shaft
  - crash
  - monstrous
  - zig
  - zig.enter
  - zig.exit
  - death
  - begin

milestone-aliases:
  god.abandon: god.renounce
  god.wor: god.worship
  unique: uniq
  unique.ban: uniq.ban
  unique.banish: uniq.ban
  uniq.banish: uniq.ban
  unique.pac: uniq.pac
  uniq.pacify: uniq.pac
  unique.pacify: uniq.pac
  unique.ens: uniq.ens
  unique.enslave: uniq.ens
  uniq.enslave: uniq.ens
  began: begin

tournament-prefixes:
  - t
  - tourney
  - tournament

tournament-data:
  default-tourney: '2013b'
  crawl:
    '2008':
      version: "0.4"
      time: [20080801, 20080901]
    '2009':
      version: "0.5"
      time: [20090801, 20090901]
    '2010':
      version: "0.7"
      time: [20100801, 20100901]
    '2011a':
      version: "0.8"
      time: [20110514, 20110530]
    '2011b':
      version: ["0.9", "0.9-a"]
      time: [20110813, 20110829]
    '2012a':
      version: "0.10"
      # Account for CDO clock being 14s slow
      time: [20120224235946, 20120312]
    '2012b':
      version: "0.11"
      time: [20121020, 20121105]
    '2013a':
      version: "0.12"
      time: [20130511, 20130527]
    '2013b':
      version: "0.13"
      time: [2013101120, 2013102720]

  sprint:
    '2010':
      version: "0.7"
      time: [20100815, 20100901]
      map: dungeon sprint mu

wtf-lookup:
  greensnark: The completely awesome variety of snark.
  tgwi: The Good Wife (according to Wikipedia)
  cang: cang
  hangedman: http://fc09.deviantart.net/fs71/i/2010/127/f/0/The_Hanged_Man_by_Luktarig.jpg
